function SimuTidy_alignDialog(parentFig)
%SimuTidy_alignDialog 创建模块对齐与分布对话框
%   SimuTidy_alignDialog(parentFig) - 在父窗口旁创建对齐对话框

    % 检查是否已有对话框打开（uifigure 默认句柄隐藏，须用 findall）
    d = findall(0, 'Type', 'figure', 'Name', '模块对齐与分布');
    if ~isempty(d)
        figure(d(1));
        return;
    end

    % 获取配置
    cfg = SimuTidy_config();

    % 创建对话框
    dlg = uifigure('Name', '模块对齐与分布', ...
                   'Position', cfg.gui.alignDialogPos, ...
                   'Color', cfg.gui.bgColor, ...
                   'Resize', 'off');

    % 对齐方式标题
    uilabel(dlg, 'Text', '对齐方式', ...
        'Position', [20, 300, 280, 24], 'FontSize', 14, ...
        'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    % 对齐按钮
    uibutton(dlg, 'push', 'Text', '左对齐', ...
        'Position', [30, 250, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'left'));

    uibutton(dlg, 'push', 'Text', '右对齐', ...
        'Position', [170, 250, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'right'));

    uibutton(dlg, 'push', 'Text', '顶部对齐', ...
        'Position', [30, 200, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'top'));

    uibutton(dlg, 'push', 'Text', '底部对齐', ...
        'Position', [170, 200, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'bottom'));

    uibutton(dlg, 'push', 'Text', '水平居中', ...
        'Position', [30, 150, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'hcenter'));

    uibutton(dlg, 'push', 'Text', '垂直居中', ...
        'Position', [170, 150, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'vcenter'));

    % 分隔线
    uilabel(dlg, 'Text', '━━━━━━━━━━━━━━━━━━━━━━', ...
        'Position', [20, 125, 280, 20], 'FontSize', 10, ...
        'FontColor', [0.7 0.7 0.7], 'HorizontalAlignment', 'center');

    % 等间距分布标题
    uilabel(dlg, 'Text', '等间距分布', ...
        'Position', [20, 105, 280, 22], 'FontSize', 13, ...
        'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    % 等间距按钮
    uibutton(dlg, 'push', 'Text', '水平等间距', ...
        'Position', [30, 55, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'hspace'));

    uibutton(dlg, 'push', 'Text', '垂直等间距', ...
        'Position', [170, 55, 120, 34], 'FontSize', 12, ...
        'BackgroundColor', cfg.colors.module, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) doAlign(parentFig, dlg, 'vspace'));

    % 关闭按钮
    uibutton(dlg, 'push', 'Text', '关闭', ...
        'Position', [110, 10, 100, 30], 'FontSize', 11, ...
        'BackgroundColor', [0.6 0.6 0.6], 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) close(dlg));
end

function doAlign(parentFig, dlg, alignType) %#ok<INUSL>
    sl = parentFig.UserData.statusLabel;
    cfg = SimuTidy_config();
    sl.Text = ['正在' getAlignText(alignType) '...'];
    sl.FontColor = cfg.colors.module;
    drawnow;
    try
        slAlignBlocks([], alignType);
        sl.Text = [getAlignText(alignType) '完成'];
        sl.FontColor = cfg.colors.success;
    catch ME
        sl.Text = ['错误: ' ME.message];
        sl.FontColor = cfg.colors.error;
    end
end

function txt = getAlignText(t)
    switch t
        case 'left',     txt = '左对齐';
        case 'right',    txt = '右对齐';
        case 'top',      txt = '顶部对齐';
        case 'bottom',   txt = '底部对齐';
        case 'hcenter',  txt = '水平居中';
        case 'vcenter',  txt = '垂直居中';
        case 'hspace',   txt = '水平等间距';
        case 'vspace',   txt = '垂直等间距';
        otherwise,       txt = '对齐';
    end
end
