function SimuTidy_onboarding()
%SimuTidy_onboarding 新手引导对话框（首次启动功能导览）
%   SimuTidy_onboarding() - 打开 3 步引导向导
%
%   说明：
%       - 单例窗口；完成时若勾选"不再自动显示"则写入 MATLAB Preferences
%       - 主窗口通过 cfg.gui.showOnboarding 与 getpref('SimuTidy','onboarded') 判断是否自动弹出

    % 单例（uifigure 默认句柄隐藏，须用 findall）
    d = findall(0, 'Type', 'figure', 'Name', 'SimuTidy 新手引导');
    if ~isempty(d)
        figure(d(1));
        return;
    end

    cfg = SimuTidy_config();

    dlg = uifigure('Name', 'SimuTidy 新手引导', ...
                   'Position', [560, 220, 480, 380], ...
                   'Color', cfg.gui.bgColor, ...
                   'Resize', 'off');

    % 存储向导状态
    dlg.UserData.page = 1;
    dlg.UserData.pages = buildPages(cfg);
    dlg.UserData.noShowBox = uicheckbox(dlg, ...
        'Text', '不再自动显示', ...
        'Position', [250, 55, 210, 16], ...
        'FontSize', 9, 'FontColor', cfg.colors.textSubtle, ...  % 3.2.0 色值入调色板
        'Value', true);

    content = uitextarea(dlg, ...
        'Position', [20, 90, 440, 240], ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 11, ...
        'Editable', 'off', ...
        'BackgroundColor', cfg.gui.bgColor);

    pageLabel = uilabel(dlg, ...
        'Position', [20, 55, 200, 18], ...
        'FontSize', 9, 'FontColor', cfg.colors.textFaint);  % 3.2.0 色值入调色板

    btnPrev = uibutton(dlg, 'push', 'Text', '上一步', ...
        'Position', [180, 14, 80, 28], 'FontSize', 11, ...
        'BackgroundColor', cfg.colors.btnGrey, 'FontColor', [1 1 1], ...  % 3.2.0 色值入调色板
        'ButtonPushedFcn', @(~,~) gotoPage(dlg, content, pageLabel, -1));

    btnNext = uibutton(dlg, 'push', 'Text', '下一步', ...
        'Position', [270, 14, 80, 28], 'FontSize', 11, ...
        'FontWeight', 'bold', 'BackgroundColor', cfg.colors.moduleDark, ...
        'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~,~) nextOrFinish(dlg, content, pageLabel));

    uibutton(dlg, 'push', 'Text', '跳过', ...
        'Position', [20, 14, 80, 28], 'FontSize', 11, ...
        'BackgroundColor', cfg.colors.btnGrey, 'FontColor', [1 1 1], ...  % 3.2.0 色值入调色板
        'ButtonPushedFcn', @(~,~) finish(dlg));

    gotoPage(dlg, content, pageLabel, 0);

    % ---- 嵌套函数 ----
    function gotoPage(src, c, pl, delta)
        p = src.UserData.page + delta;
        p = max(1, min(numel(src.UserData.pages), p));
        src.UserData.page = p;
        c.Value = src.UserData.pages{p};
        pl.Text = sprintf('第 %d / %d 页', p, numel(src.UserData.pages));
        btnPrev.Enable = (p > 1);
        if p == numel(src.UserData.pages)
            btnNext.Text = '完成';
        else
            btnNext.Text = '下一步';
        end
    end

    function nextOrFinish(src, c, pl)
        if src.UserData.page < numel(src.UserData.pages)
            gotoPage(src, c, pl, 1);
        else
            finish(src);
        end
    end

    function finish(src)
        if src.UserData.noShowBox.Value
            try
                setpref('SimuTidy', 'onboarded', true);
            catch
            end
        end
        delete(src);
    end
end

%% ========================================================================
%  页面内容
%% ========================================================================
function out = buildPages(cfg)
    out = { ...
    sprintf(['欢迎使用 SimuTidy — Simulink 建模辅助小工具！\n\n' ...
             'SimuTidy 把 Simulink 模型整理中的重复操作做成一键功能：\n' ...
             '模块对齐、大小统一、连线端口对齐、信号线命名、\n' ...
             'Goto/From 批量拆分、生成接口、批量改名、未连接检查……\n\n' ...
             '当前版本：%s（%s）'], cfg.version, cfg.versionDate), ...
    sprintf(['主窗口按功能分为 5 个分区（按钮颜色即分区）：\n\n' ...
             '  1. 视图与导出：导出 Web 视图 ZIP\n' ...
             '  2. 模块整理：8 种对齐/等间距、大小统一\n' ...
             '  3. 连线整理：连线端口对齐、信号线命名、拆分 Goto/From\n' ...
             '  4. 接口与命名：生成接口、更新模块名称\n' ...
             '  5. 检查与诊断：高亮未连接端口\n\n' ...
             '已安装 Simulink Toolstrip 选项卡的用户，也可在顶部\n' ...
             '工具条"格式"与"APP"之间的 SimuTidy 选项卡中使用全部功能。']), ...
    sprintf(['使用提示：\n\n' ...
             '  - 先在模型中选中对象（模块/连线），再点击对应按钮\n' ...
             '  - 鼠标悬停在按钮上可查看功能说明\n' ...
             '  - 所有操作可在 Simulink 中 Ctrl+Z 撤销\n' ...
             '  - 批量操作结果在 MATLAB 命令行汇总（成功/跳过及原因）\n' ...
             '  - 完整文档见项目目录下 USER_GUIDE.md\n\n' ...
             '开发者：Henry | 1378099981@qq.com | github.com/zyd180\n\n' ...
             '祝你使用愉快！'])};
end
